export const Countries = [
  { name: "Aruba", code: "AW", phoneCode: "+516", flag: "🇦🇼", minLength: 8, maxLength: 12 },
  { name: "Afghanistan", code: "AF", phoneCode: "+484", flag: "🇦🇫", minLength: 8, maxLength: 12 },
  { name: "Angola", code: "AO", phoneCode: "+513", flag: "🇦🇴", minLength: 8, maxLength: 12 },
  { name: "Anguilla", code: "AI", phoneCode: "+920", flag: "🇦🇮", minLength: 8, maxLength: 12 },
  { name: "Åland Islands", code: "AX", phoneCode: "+283", flag: "🇦🇽", minLength: 8, maxLength: 12 },
  { name: "Albania", code: "AL", phoneCode: "+381", flag: "🇦🇱", minLength: 8, maxLength: 12 },
  { name: "Andorra", code: "AD", phoneCode: "+435", flag: "🇦🇩", minLength: 8, maxLength: 12 },
  { name: "United Arab Emirates", code: "AE", phoneCode: "+971", flag: "🇦🇪", minLength: 9, maxLength: 9 },
  { name: "Argentina", code: "AR", phoneCode: "+54", flag: "🇦🇷", minLength: 10, maxLength: 10 },
  { name: "Armenia", code: "AM", phoneCode: "+788", flag: "🇦🇲", minLength: 8, maxLength: 12 },
  { name: "American Samoa", code: "AS", phoneCode: "+868", flag: "🇦🇸", minLength: 8, maxLength: 12 },
  { name: "Antarctica", code: "AQ", phoneCode: "+857", flag: "🇦🇶", minLength: 8, maxLength: 12 },
  { name: "French Southern Territories", code: "TF", phoneCode: "+687", flag: "🇹🇫", minLength: 8, maxLength: 12 },
  { name: "Antigua and Barbuda", code: "AG", phoneCode: "+213", flag: "🇦🇬", minLength: 8, maxLength: 12 },
  { name: "Australia", code: "AU", phoneCode: "+61", flag: "🇦🇺", minLength: 9, maxLength: 9 },
  { name: "Austria", code: "AT", phoneCode: "+901", flag: "🇦🇹", minLength: 8, maxLength: 12 },
  { name: "Azerbaijan", code: "AZ", phoneCode: "+883", flag: "🇦🇿", minLength: 8, maxLength: 12 },
  { name: "Burundi", code: "BI", phoneCode: "+940", flag: "🇧🇮", minLength: 8, maxLength: 12 },
  { name: "Belgium", code: "BE", phoneCode: "+964", flag: "🇧🇪", minLength: 8, maxLength: 12 },
  { name: "Benin", code: "BJ", phoneCode: "+202", flag: "🇧🇯", minLength: 8, maxLength: 12 },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ", phoneCode: "+947", flag: "🇧🇶", minLength: 8, maxLength: 12 },
  { name: "Burkina Faso", code: "BF", phoneCode: "+631", flag: "🇧🇫", minLength: 8, maxLength: 12 },
  { name: "Bangladesh", code: "BD", phoneCode: "+870", flag: "🇧🇩", minLength: 8, maxLength: 12 },
  { name: "Bulgaria", code: "BG", phoneCode: "+501", flag: "🇧🇬", minLength: 8, maxLength: 12 },
  { name: "Bahrain", code: "BH", phoneCode: "+697", flag: "🇧🇭", minLength: 8, maxLength: 12 },
  { name: "Bahamas", code: "BS", phoneCode: "+657", flag: "🇧🇸", minLength: 8, maxLength: 12 },
  { name: "Bosnia and Herzegovina", code: "BA", phoneCode: "+615", flag: "🇧🇦", minLength: 8, maxLength: 12 },
  { name: "Saint Barthélemy", code: "BL", phoneCode: "+596", flag: "🇧🇱", minLength: 8, maxLength: 12 },
  { name: "Belarus", code: "BY", phoneCode: "+975", flag: "🇧🇾", minLength: 8, maxLength: 12 },
  { name: "Belize", code: "BZ", phoneCode: "+561", flag: "🇧🇿", minLength: 8, maxLength: 12 },
  { name: "Bermuda", code: "BM", phoneCode: "+665", flag: "🇧🇲", minLength: 8, maxLength: 12 },
  { name: "Bolivia, Plurinational State of", code: "BO", phoneCode: "+506", flag: "🇧🇴", minLength: 8, maxLength: 12 },
  { name: "Brazil", code: "BR", phoneCode: "+55", flag: "🇧🇷", minLength: 10, maxLength: 11 },
  { name: "Barbados", code: "BB", phoneCode: "+421", flag: "🇧🇧", minLength: 8, maxLength: 12 },
  { name: "Brunei Darussalam", code: "BN", phoneCode: "+242", flag: "🇧🇳", minLength: 8, maxLength: 12 },
  { name: "Bhutan", code: "BT", phoneCode: "+831", flag: "🇧🇹", minLength: 8, maxLength: 12 },
  { name: "Bouvet Island", code: "BV", phoneCode: "+118", flag: "🇧🇻", minLength: 8, maxLength: 12 },
  { name: "Botswana", code: "BW", phoneCode: "+941", flag: "🇧🇼", minLength: 8, maxLength: 12 },
  { name: "Central African Republic", code: "CF", phoneCode: "+521", flag: "🇨🇫", minLength: 8, maxLength: 12 },
  { name: "Canada", code: "CA", phoneCode: "+1", flag: "🇨🇦", minLength: 10, maxLength: 10 },
  { name: "Cocos (Keeling) Islands", code: "CC", phoneCode: "+945", flag: "🇨🇨", minLength: 8, maxLength: 12 },
  { name: "Switzerland", code: "CH", phoneCode: "+633", flag: "🇨🇭", minLength: 8, maxLength: 12 },
  { name: "Chile", code: "CL", phoneCode: "+498", flag: "🇨🇱", minLength: 8, maxLength: 12 },
  { name: "China", code: "CN", phoneCode: "+86", flag: "🇨🇳", minLength: 11, maxLength: 11 },
  { name: "Côte d'Ivoire", code: "CI", phoneCode: "+454", flag: "🇨🇮", minLength: 8, maxLength: 12 },
  { name: "Cameroon", code: "CM", phoneCode: "+245", flag: "🇨🇲", minLength: 8, maxLength: 12 },
  { name: "Congo, The Democratic Republic of the", code: "CD", phoneCode: "+776", flag: "🇨🇩", minLength: 8, maxLength: 12 },
  { name: "Congo", code: "CG", phoneCode: "+902", flag: "🇨🇬", minLength: 8, maxLength: 12 },
  { name: "Cook Islands", code: "CK", phoneCode: "+657", flag: "🇨🇰", minLength: 8, maxLength: 12 },
  { name: "Colombia", code: "CO", phoneCode: "+231", flag: "🇨🇴", minLength: 8, maxLength: 12 },
  { name: "Comoros", code: "KM", phoneCode: "+806", flag: "🇰🇲", minLength: 8, maxLength: 12 },
  { name: "Cabo Verde", code: "CV", phoneCode: "+593", flag: "🇨🇻", minLength: 8, maxLength: 12 },
  { name: "Costa Rica", code: "CR", phoneCode: "+106", flag: "🇨🇷", minLength: 8, maxLength: 12 },
  { name: "Cuba", code: "CU", phoneCode: "+108", flag: "🇨🇺", minLength: 8, maxLength: 12 },
  { name: "Curaçao", code: "CW", phoneCode: "+212", flag: "🇨🇼", minLength: 8, maxLength: 12 },
  { name: "Christmas Island", code: "CX", phoneCode: "+940", flag: "🇨🇽", minLength: 8, maxLength: 12 },
  { name: "Cayman Islands", code: "KY", phoneCode: "+190", flag: "🇰🇾", minLength: 8, maxLength: 12 },
  { name: "Cyprus", code: "CY", phoneCode: "+526", flag: "🇨🇾", minLength: 8, maxLength: 12 },
  { name: "Czechia", code: "CZ", phoneCode: "+904", flag: "🇨🇿", minLength: 8, maxLength: 12 },
  { name: "Germany", code: "DE", phoneCode: "+49", flag: "🇩🇪", minLength: 10, maxLength: 11 },
  { name: "Djibouti", code: "DJ", phoneCode: "+216", flag: "🇩🇯", minLength: 8, maxLength: 12 },
  { name: "Dominica", code: "DM", phoneCode: "+196", flag: "🇩🇲", minLength: 8, maxLength: 12 },
  { name: "Denmark", code: "DK", phoneCode: "+113", flag: "🇩🇰", minLength: 8, maxLength: 12 },
  { name: "Dominican Republic", code: "DO", phoneCode: "+867", flag: "🇩🇴", minLength: 8, maxLength: 12 },
  { name: "Algeria", code: "DZ", phoneCode: "+254", flag: "🇩🇿", minLength: 8, maxLength: 12 },
  { name: "Ecuador", code: "EC", phoneCode: "+154", flag: "🇪🇨", minLength: 8, maxLength: 12 },
  { name: "Egypt", code: "EG", phoneCode: "+632", flag: "🇪🇬", minLength: 8, maxLength: 12 },
  { name: "Eritrea", code: "ER", phoneCode: "+290", flag: "🇪🇷", minLength: 8, maxLength: 12 },
  { name: "Western Sahara", code: "EH", phoneCode: "+408", flag: "🇪🇭", minLength: 8, maxLength: 12 },
  { name: "Spain", code: "ES", phoneCode: "+34", flag: "🇪🇸", minLength: 9, maxLength: 9 },
  { name: "Estonia", code: "EE", phoneCode: "+205", flag: "🇪🇪", minLength: 8, maxLength: 12 },
  { name: "Ethiopia", code: "ET", phoneCode: "+516", flag: "🇪🇹", minLength: 8, maxLength: 12 },
  { name: "Finland", code: "FI", phoneCode: "+296", flag: "🇫🇮", minLength: 8, maxLength: 12 },
  { name: "Fiji", code: "FJ", phoneCode: "+308", flag: "🇫🇯", minLength: 8, maxLength: 12 },
  { name: "Falkland Islands (Malvinas)", code: "FK", phoneCode: "+951", flag: "🇫🇰", minLength: 8, maxLength: 12 },
  { name: "France", code: "FR", phoneCode: "+33", flag: "🇫🇷", minLength: 9, maxLength: 9 },
  { name: "Faroe Islands", code: "FO", phoneCode: "+545", flag: "🇫🇴", minLength: 8, maxLength: 12 },
  { name: "Micronesia, Federated States of", code: "FM", phoneCode: "+814", flag: "🇫🇲", minLength: 8, maxLength: 12 },
  { name: "Gabon", code: "GA", phoneCode: "+732", flag: "🇬🇦", minLength: 8, maxLength: 12 },
  { name: "United Kingdom", code: "GB", phoneCode: "+44", flag: "🇬🇧", minLength: 10, maxLength: 10 },
  { name: "Georgia", code: "GE", phoneCode: "+857", flag: "🇬🇪", minLength: 8, maxLength: 12 },
  { name: "Guernsey", code: "GG", phoneCode: "+801", flag: "🇬🇬", minLength: 8, maxLength: 12 },
  { name: "Ghana", code: "GH", phoneCode: "+791", flag: "🇬🇭", minLength: 8, maxLength: 12 },
  { name: "Gibraltar", code: "GI", phoneCode: "+533", flag: "🇬🇮", minLength: 8, maxLength: 12 },
  { name: "Guinea", code: "GN", phoneCode: "+783", flag: "🇬🇳", minLength: 8, maxLength: 12 },
  { name: "Guadeloupe", code: "GP", phoneCode: "+791", flag: "🇬🇵", minLength: 8, maxLength: 12 },
  { name: "Gambia", code: "GM", phoneCode: "+391", flag: "🇬🇲", minLength: 8, maxLength: 12 },
  { name: "Guinea-Bissau", code: "GW", phoneCode: "+622", flag: "🇬🇼", minLength: 8, maxLength: 12 },
  { name: "Equatorial Guinea", code: "GQ", phoneCode: "+316", flag: "🇬🇶", minLength: 8, maxLength: 12 },
  { name: "Greece", code: "GR", phoneCode: "+560", flag: "🇬🇷", minLength: 8, maxLength: 12 },
  { name: "Grenada", code: "GD", phoneCode: "+597", flag: "🇬🇩", minLength: 8, maxLength: 12 },
  { name: "Greenland", code: "GL", phoneCode: "+924", flag: "🇬🇱", minLength: 8, maxLength: 12 },
  { name: "Guatemala", code: "GT", phoneCode: "+539", flag: "🇬🇹", minLength: 8, maxLength: 12 },
  { name: "French Guiana", code: "GF", phoneCode: "+134", flag: "🇬🇫", minLength: 8, maxLength: 12 },
  { name: "Guam", code: "GU", phoneCode: "+350", flag: "🇬🇺", minLength: 8, maxLength: 12 },
  { name: "Guyana", code: "GY", phoneCode: "+990", flag: "🇬🇾", minLength: 8, maxLength: 12 },
  { name: "Hong Kong", code: "HK", phoneCode: "+656", flag: "🇭🇰", minLength: 8, maxLength: 12 },
  { name: "Heard Island and McDonald Islands", code: "HM", phoneCode: "+306", flag: "🇭🇲", minLength: 8, maxLength: 12 },
  { name: "Honduras", code: "HN", phoneCode: "+973", flag: "🇭🇳", minLength: 8, maxLength: 12 },
  { name: "Croatia", code: "HR", phoneCode: "+108", flag: "🇭🇷", minLength: 8, maxLength: 12 },
  { name: "Haiti", code: "HT", phoneCode: "+351", flag: "🇭🇹", minLength: 8, maxLength: 12 },
  { name: "Hungary", code: "HU", phoneCode: "+340", flag: "🇭🇺", minLength: 8, maxLength: 12 },
  { name: "Indonesia", code: "ID", phoneCode: "+62", flag: "🇮🇩", minLength: 10, maxLength: 11 },
  { name: "Isle of Man", code: "IM", phoneCode: "+739", flag: "🇮🇲", minLength: 8, maxLength: 12 },
  { name: "India", code: "IN", phoneCode: "+91", flag: "🇮🇳", minLength: 10, maxLength: 10 },
  { name: "British Indian Ocean Territory", code: "IO", phoneCode: "+410", flag: "🇮🇴", minLength: 8, maxLength: 12 },
  { name: "Ireland", code: "IE", phoneCode: "+711", flag: "🇮🇪", minLength: 8, maxLength: 12 },
  { name: "Iran, Islamic Republic of", code: "IR", phoneCode: "+614", flag: "🇮🇷", minLength: 8, maxLength: 12 },
  { name: "Iraq", code: "IQ", phoneCode: "+400", flag: "🇮🇶", minLength: 8, maxLength: 12 },
  { name: "Iceland", code: "IS", phoneCode: "+302", flag: "🇮🇸", minLength: 8, maxLength: 12 },
  { name: "Israel", code: "IL", phoneCode: "+420", flag: "🇮🇱", minLength: 8, maxLength: 12 },
  { name: "Italy", code: "IT", phoneCode: "+39", flag: "🇮🇹", minLength: 9, maxLength: 10 },
  { name: "Jamaica", code: "JM", phoneCode: "+390", flag: "🇯🇲", minLength: 8, maxLength: 12 },
  { name: "Jersey", code: "JE", phoneCode: "+442", flag: "🇯🇪", minLength: 8, maxLength: 12 },
  { name: "Jordan", code: "JO", phoneCode: "+139", flag: "🇯🇴", minLength: 8, maxLength: 12 },
  { name: "Japan", code: "JP", phoneCode: "+81", flag: "🇯🇵", minLength: 10, maxLength: 11 },
  { name: "Kazakhstan", code: "KZ", phoneCode: "+138", flag: "🇰🇿", minLength: 8, maxLength: 12 },
  { name: "Kenya", code: "KE", phoneCode: "+319", flag: "🇰🇪", minLength: 8, maxLength: 12 },
  { name: "Kyrgyzstan", code: "KG", phoneCode: "+117", flag: "🇰🇬", minLength: 8, maxLength: 12 },
  { name: "Cambodia", code: "KH", phoneCode: "+385", flag: "🇰🇭", minLength: 8, maxLength: 12 },
  { name: "Kiribati", code: "KI", phoneCode: "+216", flag: "🇰🇮", minLength: 8, maxLength: 12 },
  { name: "Saint Kitts and Nevis", code: "KN", phoneCode: "+113", flag: "🇰🇳", minLength: 8, maxLength: 12 },
  { name: "Korea, Republic of", code: "KR", phoneCode: "+82", flag: "🇰🇷", minLength: 9, maxLength: 10 },
  { name: "Kuwait", code: "KW", phoneCode: "+354", flag: "🇰🇼", minLength: 8, maxLength: 12 },
  { name: "Lao People's Democratic Republic", code: "LA", phoneCode: "+935", flag: "🇱🇦", minLength: 8, maxLength: 12 },
  { name: "Lebanon", code: "LB", phoneCode: "+638", flag: "🇱🇧", minLength: 8, maxLength: 12 },
  { name: "Liberia", code: "LR", phoneCode: "+305", flag: "🇱🇷", minLength: 8, maxLength: 12 },
  { name: "Libya", code: "LY", phoneCode: "+973", flag: "🇱🇾", minLength: 8, maxLength: 12 },
  { name: "Saint Lucia", code: "LC", phoneCode: "+169", flag: "🇱🇨", minLength: 8, maxLength: 12 },
  { name: "Liechtenstein", code: "LI", phoneCode: "+522", flag: "🇱🇮", minLength: 8, maxLength: 12 },
  { name: "Sri Lanka", code: "LK", phoneCode: "+712", flag: "🇱🇰", minLength: 8, maxLength: 12 },
  { name: "Lesotho", code: "LS", phoneCode: "+583", flag: "🇱🇸", minLength: 8, maxLength: 12 },
  { name: "Lithuania", code: "LT", phoneCode: "+292", flag: "🇱🇹", minLength: 8, maxLength: 12 },
  { name: "Luxembourg", code: "LU", phoneCode: "+185", flag: "🇱🇺", minLength: 8, maxLength: 12 },
  { name: "Latvia", code: "LV", phoneCode: "+806", flag: "🇱🇻", minLength: 8, maxLength: 12 },
  { name: "Macao", code: "MO", phoneCode: "+171", flag: "🇲🇴", minLength: 8, maxLength: 12 },
  { name: "Saint Martin (French part)", code: "MF", phoneCode: "+241", flag: "🇲🇫", minLength: 8, maxLength: 12 },
  { name: "Morocco", code: "MA", phoneCode: "+447", flag: "🇲🇦", minLength: 8, maxLength: 12 },
  { name: "Monaco", code: "MC", phoneCode: "+488", flag: "🇲🇨", minLength: 8, maxLength: 12 },
  { name: "Moldova, Republic of", code: "MD", phoneCode: "+734", flag: "🇲🇩", minLength: 8, maxLength: 12 },
  { name: "Madagascar", code: "MG", phoneCode: "+445", flag: "🇲🇬", minLength: 8, maxLength: 12 },
  { name: "Maldives", code: "MV", phoneCode: "+728", flag: "🇲🇻", minLength: 8, maxLength: 12 },
  { name: "Mexico", code: "MX", phoneCode: "+52", flag: "🇲🇽", minLength: 10, maxLength: 10 },
  { name: "Marshall Islands", code: "MH", phoneCode: "+968", flag: "🇲🇭", minLength: 8, maxLength: 12 },
  { name: "North Macedonia", code: "MK", phoneCode: "+292", flag: "🇲🇰", minLength: 8, maxLength: 12 },
  { name: "Mali", code: "ML", phoneCode: "+643", flag: "🇲🇱", minLength: 8, maxLength: 12 },
  { name: "Malta", code: "MT", phoneCode: "+536", flag: "🇲🇹", minLength: 8, maxLength: 12 },
  { name: "Myanmar", code: "MM", phoneCode: "+338", flag: "🇲🇲", minLength: 8, maxLength: 12 },
  { name: "Montenegro", code: "ME", phoneCode: "+421", flag: "🇲🇪", minLength: 8, maxLength: 12 },
  { name: "Mongolia", code: "MN", phoneCode: "+457", flag: "🇲🇳", minLength: 8, maxLength: 12 },
  { name: "Northern Mariana Islands", code: "MP", phoneCode: "+660", flag: "🇲🇵", minLength: 8, maxLength: 12 },
  { name: "Mozambique", code: "MZ", phoneCode: "+847", flag: "🇲🇿", minLength: 8, maxLength: 12 },
  { name: "Mauritania", code: "MR", phoneCode: "+937", flag: "🇲🇷", minLength: 8, maxLength: 12 },
  { name: "Montserrat", code: "MS", phoneCode: "+846", flag: "🇲🇸", minLength: 8, maxLength: 12 },
  { name: "Martinique", code: "MQ", phoneCode: "+187", flag: "🇲🇶", minLength: 8, maxLength: 12 },
  { name: "Mauritius", code: "MU", phoneCode: "+380", flag: "🇲🇺", minLength: 8, maxLength: 12 },
  { name: "Malawi", code: "MW", phoneCode: "+248", flag: "🇲🇼", minLength: 8, maxLength: 12 },
  { name: "Malaysia", code: "MY", phoneCode: "+60", flag: "🇲🇾", minLength: 9, maxLength: 10 },
  { name: "Mayotte", code: "YT", phoneCode: "+759", flag: "🇾🇹", minLength: 8, maxLength: 12 },
  { name: "Namibia", code: "NA", phoneCode: "+131", flag: "🇳🇦", minLength: 8, maxLength: 12 },
  { name: "New Caledonia", code: "NC", phoneCode: "+768", flag: "🇳🇨", minLength: 8, maxLength: 12 },
  { name: "Niger", code: "NE", phoneCode: "+817", flag: "🇳🇪", minLength: 8, maxLength: 12 },
  { name: "Norfolk Island", code: "NF", phoneCode: "+443", flag: "🇳🇫", minLength: 8, maxLength: 12 },
  { name: "Nigeria", code: "NG", phoneCode: "+476", flag: "🇳🇬", minLength: 8, maxLength: 12 },
  { name: "Nicaragua", code: "NI", phoneCode: "+143", flag: "🇳🇮", minLength: 8, maxLength: 12 },
  { name: "Niue", code: "NU", phoneCode: "+672", flag: "🇳🇺", minLength: 8, maxLength: 12 },
  { name: "Netherlands", code: "NL", phoneCode: "+244", flag: "🇳🇱", minLength: 8, maxLength: 12 },
  { name: "Norway", code: "NO", phoneCode: "+398", flag: "🇳🇴", minLength: 8, maxLength: 12 },
  { name: "Nepal", code: "NP", phoneCode: "+395", flag: "🇳🇵", minLength: 8, maxLength: 12 },
  { name: "Nauru", code: "NR", phoneCode: "+920", flag: "🇳🇷", minLength: 8, maxLength: 12 },
  { name: "New Zealand", code: "NZ", phoneCode: "+64", flag: "🇳🇿", minLength: 8, maxLength: 9 },
  { name: "Oman", code: "OM", phoneCode: "+958", flag: "🇴🇲", minLength: 8, maxLength: 12 },
  { name: "Pakistan", code: "PK", phoneCode: "+686", flag: "🇵🇰", minLength: 8, maxLength: 12 },
  { name: "Panama", code: "PA", phoneCode: "+313", flag: "🇵🇦", minLength: 8, maxLength: 12 },
  { name: "Pitcairn", code: "PN", phoneCode: "+156", flag: "🇵🇳", minLength: 8, maxLength: 12 },
  { name: "Peru", code: "PE", phoneCode: "+404", flag: "🇵🇪", minLength: 8, maxLength: 12 },
  { name: "Philippines", code: "PH", phoneCode: "+572", flag: "🇵🇭", minLength: 8, maxLength: 12 },
  { name: "Palau", code: "PW", phoneCode: "+398", flag: "🇵🇼", minLength: 8, maxLength: 12 },
  { name: "Papua New Guinea", code: "PG", phoneCode: "+143", flag: "🇵🇬", minLength: 8, maxLength: 12 },
  { name: "Poland", code: "PL", phoneCode: "+437", flag: "🇵🇱", minLength: 8, maxLength: 12 },
  { name: "Puerto Rico", code: "PR", phoneCode: "+784", flag: "🇵🇷", minLength: 8, maxLength: 12 },
  { name: "Korea, Democratic People's Republic of", code: "KP", phoneCode: "+855", flag: "🇰🇵", minLength: 8, maxLength: 12 },
  { name: "Portugal", code: "PT", phoneCode: "+860", flag: "🇵🇹", minLength: 8, maxLength: 12 },
  { name: "Paraguay", code: "PY", phoneCode: "+304", flag: "🇵🇾", minLength: 8, maxLength: 12 },
  { name: "Palestine, State of", code: "PS", phoneCode: "+244", flag: "🇵🇸", minLength: 8, maxLength: 12 },
  { name: "French Polynesia", code: "PF", phoneCode: "+496", flag: "🇵🇫", minLength: 8, maxLength: 12 },
  { name: "Qatar", code: "QA", phoneCode: "+132", flag: "🇶🇦", minLength: 8, maxLength: 12 },
  { name: "Réunion", code: "RE", phoneCode: "+991", flag: "🇷🇪", minLength: 8, maxLength: 12 },
  { name: "Romania", code: "RO", phoneCode: "+508", flag: "🇷🇴", minLength: 8, maxLength: 12 },
  { name: "Russian Federation", code: "RU", phoneCode: "+7", flag: "🇷🇺", minLength: 10, maxLength: 10 },
  { name: "Rwanda", code: "RW", phoneCode: "+705", flag: "🇷🇼", minLength: 8, maxLength: 12 },
  { name: "Saudi Arabia", code: "SA", phoneCode: "+338", flag: "🇸🇦", minLength: 8, maxLength: 12 },
  { name: "Sudan", code: "SD", phoneCode: "+324", flag: "🇸🇩", minLength: 8, maxLength: 12 },
  { name: "Senegal", code: "SN", phoneCode: "+600", flag: "🇸🇳", minLength: 8, maxLength: 12 },
  { name: "Singapore", code: "SG", phoneCode: "+65", flag: "🇸🇬", minLength: 8, maxLength: 8 },
  { name: "South Georgia and the South Sandwich Islands", code: "GS", phoneCode: "+911", flag: "🇬🇸", minLength: 8, maxLength: 12 },
  { name: "Saint Helena, Ascension and Tristan da Cunha", code: "SH", phoneCode: "+678", flag: "🇸🇭", minLength: 8, maxLength: 12 },
  { name: "Svalbard and Jan Mayen", code: "SJ", phoneCode: "+136", flag: "🇸🇯", minLength: 8, maxLength: 12 },
  { name: "Solomon Islands", code: "SB", phoneCode: "+523", flag: "🇸🇧", minLength: 8, maxLength: 12 },
  { name: "Sierra Leone", code: "SL", phoneCode: "+100", flag: "🇸🇱", minLength: 8, maxLength: 12 },
  { name: "El Salvador", code: "SV", phoneCode: "+107", flag: "🇸🇻", minLength: 8, maxLength: 12 },
  { name: "San Marino", code: "SM", phoneCode: "+518", flag: "🇸🇲", minLength: 8, maxLength: 12 },
  { name: "Somalia", code: "SO", phoneCode: "+572", flag: "🇸🇴", minLength: 8, maxLength: 12 },
  { name: "Saint Pierre and Miquelon", code: "PM", phoneCode: "+224", flag: "🇵🇲", minLength: 8, maxLength: 12 },
  { name: "Serbia", code: "RS", phoneCode: "+810", flag: "🇷🇸", minLength: 8, maxLength: 12 },
  { name: "South Sudan", code: "SS", phoneCode: "+297", flag: "🇸🇸", minLength: 8, maxLength: 12 },
  { name: "Sao Tome and Principe", code: "ST", phoneCode: "+578", flag: "🇸🇹", minLength: 8, maxLength: 12 },
  { name: "Suriname", code: "SR", phoneCode: "+803", flag: "🇸🇷", minLength: 8, maxLength: 12 },
  { name: "Slovakia", code: "SK", phoneCode: "+139", flag: "🇸🇰", minLength: 8, maxLength: 12 },
  { name: "Slovenia", code: "SI", phoneCode: "+116", flag: "🇸🇮", minLength: 8, maxLength: 12 },
  { name: "Sweden", code: "SE", phoneCode: "+984", flag: "🇸🇪", minLength: 8, maxLength: 12 },
  { name: "Eswatini", code: "SZ", phoneCode: "+395", flag: "🇸🇿", minLength: 8, maxLength: 12 },
  { name: "Sint Maarten (Dutch part)", code: "SX", phoneCode: "+562", flag: "🇸🇽", minLength: 8, maxLength: 12 },
  { name: "Seychelles", code: "SC", phoneCode: "+795", flag: "🇸🇨", minLength: 8, maxLength: 12 },
  { name: "Syrian Arab Republic", code: "SY", phoneCode: "+552", flag: "🇸🇾", minLength: 8, maxLength: 12 },
  { name: "Turks and Caicos Islands", code: "TC", phoneCode: "+399", flag: "🇹🇨", minLength: 8, maxLength: 12 },
  { name: "Chad", code: "TD", phoneCode: "+800", flag: "🇹🇩", minLength: 8, maxLength: 12 },
  { name: "Togo", code: "TG", phoneCode: "+626", flag: "🇹🇬", minLength: 8, maxLength: 12 },
  { name: "Thailand", code: "TH", phoneCode: "+66", flag: "🇹🇭", minLength: 9, maxLength: 9 },
  { name: "Tajikistan", code: "TJ", phoneCode: "+401", flag: "🇹🇯", minLength: 8, maxLength: 12 },
  { name: "Tokelau", code: "TK", phoneCode: "+574", flag: "🇹🇰", minLength: 8, maxLength: 12 },
  { name: "Turkmenistan", code: "TM", phoneCode: "+940", flag: "🇹🇲", minLength: 8, maxLength: 12 },
  { name: "Timor-Leste", code: "TL", phoneCode: "+922", flag: "🇹🇱", minLength: 8, maxLength: 12 },
  { name: "Tonga", code: "TO", phoneCode: "+747", flag: "🇹🇴", minLength: 8, maxLength: 12 },
  { name: "Trinidad and Tobago", code: "TT", phoneCode: "+816", flag: "🇹🇹", minLength: 8, maxLength: 12 },
  { name: "Tunisia", code: "TN", phoneCode: "+247", flag: "🇹🇳", minLength: 8, maxLength: 12 },
  { name: "Turkey", code: "TR", phoneCode: "+370", flag: "🇹🇷", minLength: 8, maxLength: 12 },
  { name: "Tuvalu", code: "TV", phoneCode: "+854", flag: "🇹🇻", minLength: 8, maxLength: 12 },
  { name: "Taiwan, Province of China", code: "TW", phoneCode: "+755", flag: "🇹🇼", minLength: 8, maxLength: 12 },
  { name: "Tanzania, United Republic of", code: "TZ", phoneCode: "+367", flag: "🇹🇿", minLength: 8, maxLength: 12 },
  { name: "Uganda", code: "UG", phoneCode: "+713", flag: "🇺🇬", minLength: 8, maxLength: 12 },
  { name: "Ukraine", code: "UA", phoneCode: "+311", flag: "🇺🇦", minLength: 8, maxLength: 12 },
  { name: "United States Minor Outlying Islands", code: "UM", phoneCode: "+161", flag: "🇺🇲", minLength: 8, maxLength: 12 },
  { name: "Uruguay", code: "UY", phoneCode: "+921", flag: "🇺🇾", minLength: 8, maxLength: 12 },
  { name: "United States", code: "US", phoneCode: "+1", flag: "🇺🇸", minLength: 10, maxLength: 10 },
  { name: "Uzbekistan", code: "UZ", phoneCode: "+861", flag: "🇺🇿", minLength: 8, maxLength: 12 },
  { name: "Holy See (Vatican City State)", code: "VA", phoneCode: "+430", flag: "🇻🇦", minLength: 8, maxLength: 12 },
  { name: "Saint Vincent and the Grenadines", code: "VC", phoneCode: "+222", flag: "🇻🇨", minLength: 8, maxLength: 12 },
  { name: "Venezuela, Bolivarian Republic of", code: "VE", phoneCode: "+915", flag: "🇻🇪", minLength: 8, maxLength: 12 },
  { name: "Virgin Islands, British", code: "VG", phoneCode: "+254", flag: "🇻🇬", minLength: 8, maxLength: 12 },
  { name: "Virgin Islands, U.S.", code: "VI", phoneCode: "+559", flag: "🇻🇮", minLength: 8, maxLength: 12 },
  { name: "Viet Nam", code: "VN", phoneCode: "+84", flag: "🇻🇳", minLength: 9, maxLength: 10 },
  { name: "Vanuatu", code: "VU", phoneCode: "+306", flag: "🇻🇺", minLength: 8, maxLength: 12 },
  { name: "Wallis and Futuna", code: "WF", phoneCode: "+941", flag: "🇼🇫", minLength: 8, maxLength: 12 },
  { name: "Samoa", code: "WS", phoneCode: "+998", flag: "🇼🇸", minLength: 8, maxLength: 12 },
  { name: "Yemen", code: "YE", phoneCode: "+374", flag: "🇾🇪", minLength: 8, maxLength: 12 },
  { name: "South Africa", code: "ZA", phoneCode: "+27", flag: "🇿🇦", minLength: 9, maxLength: 9 },
  { name: "Zambia", code: "ZM", phoneCode: "+530", flag: "🇿🇲", minLength: 8, maxLength: 12 },
  { name: "Zimbabwe", code: "ZW", phoneCode: "+371", flag: "🇿🇼", minLength: 8, maxLength: 12 },
];
